// Code generated by Petra. DO NOT EDIT.

// here we have 3 rocks
module.exports.GABBRO = "Gabbro";
module.exports.MARBLE = "Marble";
module.exports.METAMORPHIC = "Metamorphic";
/*
let's talk about numbers,
for example we can talk about amount of fruits


*/
module.exports.APPLES_COUNT = 236;
module.exports.ORANGES_COUNT = 454588979794318;
