/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package red.java;

import static org.junit.Assert.assertEquals;

import model.Defs;
import org.junit.Test;

public class DefsTest {
  @Test
  public void defsReturnCorrectValues() {
    assertEquals(Defs.Gabbro, "Gabbro");
    assertEquals(Defs.Marble, "Marble");
    assertEquals(Defs.Metamorphic, "Metamorphic");
    assertEquals(Defs.ApplesCount, 236);
    assertEquals(Defs.OrangesCount, 454588979794318L);
  }
}
