use petra_backend_core::Name;

const DEFAULT_NAMESPACE_NAME: &str = "Defs";
const DEFAULT_CLASS_NAME: &str = "Defs";
pub const AUTO_GENERATED_COMMENT: &[u8] = b"// <auto-generated />\n";

// Personal choice
#[allow(clippy::module_name_repetitions)]
pub struct PetraCSharpConfiguration {
    namespace_name: String,
    class_name: String,
}
impl PetraCSharpConfiguration {
    #[must_use]
    pub fn new(namespace_name: Option<Name>, class_name: Option<Name>) -> Self {
        let namespace_name =
            namespace_name.map_or_else(|| DEFAULT_NAMESPACE_NAME.into(), |x| x.to_pascal_case());
        let class_name: String =
            class_name.map_or_else(|| DEFAULT_CLASS_NAME.into(), |x| x.to_pascal_case());

        Self {
            namespace_name,
            class_name,
        }
    }
    #[must_use]
    pub fn get_namespace_name(&self) -> &str {
        &self.namespace_name
    }
    #[must_use]
    pub fn get_class_name(&self) -> &str {
        &self.class_name
    }
}
impl Default for PetraCSharpConfiguration {
    fn default() -> Self {
        Self::new(None, None)
    }
}
