    // Code generated by Petra. DO NOT EDIT.

namespace Defs;
public static class Defs
{
    // here we have 3 rocks
    public const string Gabbro = "Gabbro";
    public const string Marble = "Marble";
    public const string Metamorphic = "Metamorphic";
/*let's talk about numbers,
for example we can talk about amount of fruits

 */
    public const long ApplesCount = 236;
    public const long OrangesCount = 454588979794318;
}
