// Code generated by Petra. DO NOT EDIT.

// here we have 3 rocks
pub const GABBRO: &str = "Gabbro";
pub const MARBLE: &str = "Marble";
pub const METAMORPHIC: &str = "Metamorphic";
/*let's talk about numbers,
for example we can talk about amount of fruits

 */
pub const APPLES_COUNT: i64 = 236;
pub const ORANGES_COUNT: i64 = 454588979794318;
