// Code generated by Petra. DO NOT EDIT.
#pragma once
namespace Defs {
// here we have 3 rocks
static const std::string gabbro = "Gabbro";
static const std::string marble = "Marble";
static const std::string metamorphic = "Metamorphic";
/* let's talk about numbers,
  for example we can talk about amount of fruits

*/
static const long apples_count = 236;
static const long oranges_count = 454588979794318;
}  // namespace Defs