use petra_backend_core::{format, MultiCommentFormatter, Name, SimpleLanguageBackend};
use std::io::Write;

#[derive(
    SimpleLanguageBackend,
    format::PetraFormatAutoGeneratedComment,
    format::PetraFormatFooter,
    format::PetraFormatHeader,
)]
pub struct PetraTsBackend {
    comment_writer: MultiCommentFormatter,
}

impl PetraTsBackend {
    #[must_use]
    pub const fn new() -> Self {
        Self {
            comment_writer: MultiCommentFormatter::new(true),
        }
    }
}

impl format::PetraFormatI64 for PetraTsBackend {
    fn format<T: Write>(&mut self, name: &Name, data: i64, writer: &mut T) -> std::io::Result<()> {
        // self.need_new_line = true;
        let name = name.to_upper_snake();
        writeln!(writer, "export const {name}: number = {data};")
    }
}
impl format::PetraFormatString for PetraTsBackend {
    fn format<T: Write>(&mut self, name: &Name, data: &str, writer: &mut T) -> std::io::Result<()> {
        let name = name.to_upper_snake();
        writeln!(writer, "export const {name}: string = \"{data}\";")
    }
}
impl format::PetraFormatLineComment for PetraTsBackend {
    fn format<T: Write>(&mut self, comment: &str, writer: &mut T) -> std::io::Result<()> {
        writeln!(writer, "// {comment}")
    }
}
impl format::PetraFormatMultiLineComment for PetraTsBackend {
    fn format<T: Write>(&mut self, comment: &str, writer: &mut T) -> std::io::Result<()> {
        self.comment_writer.format(comment, "", writer)
    }
}
