// Code generated by Petra. DO NOT EDIT.

package model;

/** Defs hold const values. */
public class Defs {
  // here we have 3 rocks
  public static final String Gabbro = "Gabbro";
  public static final String Marble = "Marble";
  public static final String Metamorphic = "Metamorphic";
  /*
  let's talk about numbers,
  for example we can talk about amount of fruits


  */
  public static final long ApplesCount = 236L;
  public static final long OrangesCount = 454588979794318L;
}
