// Code generated by Petra. DO NOT EDIT.

package defs

// here we have 3 rocks
const Gabbro = "Gabbro"
const Marble = "Marble"
const Metamorphic = "Metamorphic"

/*
let's talk about numbers,
for example we can talk about amount of fruits
*/
const ApplesCount = 236
const OrangesCount = 454588979794318
