// Code generated by Petra. DO NOT EDIT.

// here we have 3 rocks
export const GABBRO: string = "Gabbro";
export const MARBLE: string = "Marble";
export const METAMORPHIC: string = "Metamorphic";
/*
let's talk about numbers,
for example we can talk about amount of fruits


*/
export const APPLES_COUNT: number = 236;
export const ORANGES_COUNT: number = 454588979794318;
