[package]
name = "petra-backend-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petra-backend-core = { path = "../petra-backend-core", version = "0.1.0" }