use super::format::{PetraFormatAutoGeneratedComment, PetraFormatHeader, PetraFormatLineComment};
use crate::defs;
use std::io::Write;

pub trait WriteHeader {
    fn write_header<T: Write>(
        &mut self,
        writer: &mut T,
        create_auto_generated_comment: bool,
    ) -> std::io::Result<()>;
}
impl<B> WriteHeader for B
where
    B: PetraFormatLineComment + PetraFormatHeader + PetraFormatAutoGeneratedComment,
{
    fn write_header<T: Write>(
        &mut self,
        writer: &mut T,
        create_auto_generated_comment: bool,
    ) -> std::io::Result<()> {
        PetraFormatLineComment::format(self, defs::GENERATED_MESSAGE, writer)?;
        writeln!(writer)?;
        if create_auto_generated_comment {
            PetraFormatAutoGeneratedComment::format(self, writer)?;
        }
        PetraFormatHeader::format(self, writer)
    }
}
