use super::format::{PetraFormatAutoGeneratedComment, PetraFormatHeader, PetraFormatLineComment};
use crate::{defs, Result};
use std::io::Write;

pub trait WriteHeader<T>
where
    T: Write,
{
    fn write_header(&self, writer: &mut T, create_auto_generated_comment: bool) -> Result<()>;
}
impl<T, B> WriteHeader<T> for B
where
    T: Write,
    B: PetraFormatLineComment + PetraFormatHeader + PetraFormatAutoGeneratedComment,
{
    fn write_header(&self, writer: &mut T, create_auto_generated_comment: bool) -> Result<()> {
        writer.write_all(&PetraFormatLineComment::format(
            self,
            defs::GENERATED_MESSAGE,
        ))?;
        writer.write_all(b"\n")?;
        if create_auto_generated_comment {
            if let Some(auto_generated_comment) = PetraFormatAutoGeneratedComment::format(self) {
                writer.write_all(&auto_generated_comment)?;
            }
        }
        if let Some(header) = PetraFormatHeader::format(self) {
            writer.write_all(&header)?;
        }
        Ok(())
    }
}
